version: '3.8'

services:
  bot:
    build: .
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    command: python bot.py

  webapp:
    build: .
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    ports:
      - "${WEBAPP_PORT:-8000}:8000"
    networks:
      - bot-network
    command: python run_webapp.py

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-coffee_bot}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres_data: